name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - env:
          MSTEST_VERSION: 3
        run: |
          echo ${MSTEST_VERSION}
          PackageBaseAddress=$(curl -fS https://pkgs.dev.azure.com/dnceng/public/_packaging/test-tools/nuget/v3/index.json | jq -r 'first(.resources[] | select(.["@type"] | startswith("PackageBaseAddress"))) | .["@id"]')
          Version=$(curl -fS ${PackageBaseAddress}/mstest/index.json | jq -r "first(.versions[] | select(startswith(\"${MSTEST_VERSION}\")))")
          curl -fSLO "${PackageBaseAddress}/mstest/${Version}/mstest.${Version}.nupkg"
          curl -fSLO "${PackageBaseAddress}/mstest/3.6.0/mstest.3.6.0.nupkg"

      - uses: moomiji/host-nuget-on-github@main
        with:
          force: true
          package-paths: ./
          branch: test-simplest
          base-uri: https://github.com/moomiji/host-nuget-on-github/raw/test-simplest/

      - uses: moomiji/host-nuget-on-github@main
        with:
          skip-existing: true
          package-paths: ./
          branch: test-squash
          base-uri: https://github.com/moomiji/host-nuget-on-github/raw/test-squash/
          squash: true

      - uses: moomiji/host-nuget-on-github@main
        with:
          skip-existing: true
          squash: true
          package-paths: ./
          branch: test-path
          base-uri: https://github.com/moomiji/host-nuget-on-github/raw/test-path/feed/
          feed-path: feed

      - uses: moomiji/host-nuget-on-github@main
        with:
          skip-existing: true
          package-paths: ./
          branch: test-commit-no-sign
          base-uri: https://github.com/moomiji/host-nuget-on-github/raw/test-commit-no-sign/
          squash: true
          commit-sign: true
